# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='demoserveruser',
            new_name='Profile',
        ),
    ]
