# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161003_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.CharField(default='admin: false, researcher: false, subject: true', max_length=200),
        ),
    ]
