# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 03:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_profile_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contentitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('acceptmsg', models.CharField(blank=True, max_length=200)),
                ('rejectmsg', models.CharField(blank=True, max_length=200)),
                ('taskdescription', models.TextField(blank=True)),
                ('dayorder', models.IntegerField(blank=True)),
                ('contentorder', models.IntegerField(blank=True)),
                ('malicious', models.BooleanField()),
                ('story', models.BooleanField()),
                ('sophistications', models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('degradations', models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('naturalfeatures', models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('active', models.BooleanField(default=True)),
                ('trust', models.NullBooleanField(default=None)),
                ('trustlevel', models.IntegerField(blank=True)),
                ('trustdate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.CharField(default='{"admin": false, "researcher": false, "subject": true}', max_length=200),
        ),
        migrations.CreateModel(
            name='Emailitem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Contentitem')),
                ('sender', models.CharField(blank=True, max_length=200)),
                ('senderemail', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('greetingline', models.CharField(blank=True, max_length=200)),
                ('emailbody', models.TextField(blank=True)),
                ('sentdate', models.DateTimeField(blank=True)),
                ('paperclip', models.BooleanField(default=False)),
            ],
            bases=('api.contentitem',),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
