# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161004_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='contentorder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='dayorder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='trustlevel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
