# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161004_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedling',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Contentitem')),
                ('feedlingbdoy', models.TextField(blank=True)),
                ('sentdate', models.DateTimeField(blank=True)),
                ('alerttype', models.CharField(blank=True, max_length=200)),
                ('authordisplayname', models.CharField(blank=True, max_length=200)),
                ('authorusername', models.CharField(blank=True, max_length=200)),
                ('authoravatarurl', models.CharField(blank=True, max_length=200)),
                ('mutualpartners', models.CharField(blank=True, max_length=500)),
            ],
            bases=('api.contentitem',),
        ),
    ]
