# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_feedling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedling',
            old_name='feedlingbdoy',
            new_name='feedlingbody',
        ),
    ]
