# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20161006_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='active',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='contentorder',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='dayorder',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='taskdescription',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='trust',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='trustdate',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='trustlevel',
        ),
        migrations.AddField(
            model_name='task',
            name='contentorder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='dayorder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='taskdescription',
            field=models.TextField(blank=True),
        ),
    ]
